---
- name: add signature for Docker repository
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: add Docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

- name: install Docker
  apt: name={{ docker_package }} state=present force=yes update_cache=yes

- name: install packages
  apt: name={{ item }} state=latest force=yes update_cache=yes
  with_items:
    - python-pip

- name: install docker-compose
  pip: name=docker-compose

- name: start Docker
  service: name=docker state=started

- name: create user and add it to group docker
  user: name={{user}} shell=/bin/bash groups=docker
